import { ISuggestion } from "../../types/suggestion";
import { IIngredient } from "../../types/ingredients";

export const suggestedRecipesExample: ISuggestion[] = [
  {
    recipeId: 15249,
    recipeName: "Recipe 15249",
    recipeUrl: "recipe-15249",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [17, 23, 3],
    suggestionScore: 0.25,
  },
  {
    recipeId: 19227,
    recipeName: "Recipe 19227",
    recipeUrl: "recipe-19227",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [29, 17, 3],
    suggestionScore: 0.25,
  },
  {
    recipeId: 26013,
    recipeName: "Recipe 26013",
    recipeUrl: "recipe-26013",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [23, 29, 3],
    suggestionScore: 0.25,
  },
  {
    recipeId: 147407,
    recipeName: "Recipe 147407",
    recipeUrl: "recipe-147407",
    cuisineId: 5,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [29, 23, 17],
    suggestionScore: 0.25,
  },
  {
    recipeId: 663,
    recipeName: "Recipe 663",
    recipeUrl: "recipe-663",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [3, 17],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 897,
    recipeName: "Recipe 897",
    recipeUrl: "recipe-897",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [3, 23],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 5083,
    recipeName: "Recipe 5083",
    recipeUrl: "recipe-5083",
    cuisineId: 7,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [17, 23],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 6409,
    recipeName: "Recipe 6409",
    recipeUrl: "recipe-6409",
    cuisineId: 10,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [17, 29],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 8671,
    recipeName: "Recipe 8671",
    recipeUrl: "recipe-8671",
    cuisineId: 4,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [23, 29],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 884442,
    recipeName: "Recipe 884442",
    recipeUrl: "recipe-884442",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [17, 29, 23, 3],
    suggestionScore: 0.3333333333333333,
  },
  {
    recipeId: 30498,
    recipeName: "Recipe 30498",
    recipeUrl: "recipe-30498",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [17, 3, 23],
    suggestionScore: 0.4,
  },
  {
    recipeId: 38454,
    recipeName: "Recipe 38454",
    recipeUrl: "recipe-38454",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [3, 17, 29],
    suggestionScore: 0.4,
  },
  {
    recipeId: 52026,
    recipeName: "Recipe 52026",
    recipeUrl: "recipe-52026",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [29, 3, 23],
    suggestionScore: 0.4,
  },
  {
    recipeId: 294814,
    recipeName: "Recipe 294814",
    recipeUrl: "recipe-294814",
    cuisineId: 10,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [17, 23, 29],
    suggestionScore: 0.4,
  },
  {
    recipeId: 221,
    recipeName: "Recipe 221",
    recipeUrl: "recipe-221",
    cuisineId: 5,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13],
    missingIngredients: [17],
    suggestionScore: 0.5,
  },
  {
    recipeId: 1326,
    recipeName: "Recipe 1326",
    recipeUrl: "recipe-1326",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [3, 17],
    suggestionScore: 0.5,
  },
  {
    recipeId: 1794,
    recipeName: "Recipe 1794",
    recipeUrl: "recipe-1794",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [23, 3],
    suggestionScore: 0.5,
  },
  {
    recipeId: 2262,
    recipeName: "Recipe 2262",
    recipeUrl: "recipe-2262",
    cuisineId: 3,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [3, 29],
    suggestionScore: 0.5,
  },
  {
    recipeId: 10166,
    recipeName: "Recipe 10166",
    recipeUrl: "recipe-10166",
    cuisineId: 5,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [17, 23],
    suggestionScore: 0.5,
  },
  {
    recipeId: 12818,
    recipeName: "Recipe 12818",
    recipeUrl: "recipe-12818",
    cuisineId: 2,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [29, 17],
    suggestionScore: 0.5,
  },
  {
    recipeId: 17342,
    recipeName: "Recipe 17342",
    recipeUrl: "recipe-17342",
    cuisineId: 8,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [23, 29],
    suggestionScore: 0.5,
  },
  {
    recipeId: 78,
    recipeName: "Recipe 78",
    recipeUrl: "recipe-78",
    cuisineId: 6,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [3],
    suggestionScore: 0.6666666666666666,
  },
  {
    recipeId: 598,
    recipeName: "Recipe 598",
    recipeUrl: "recipe-598",
    cuisineId: 4,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [13, 2],
    missingIngredients: [23],
    suggestionScore: 0.6666666666666666,
  },
  {
    recipeId: 754,
    recipeName: "Recipe 754",
    recipeUrl: "recipe-754",
    cuisineId: 7,
    recipeSuggestedTimes: 0,
    recipeIngredientsAverageCommonness: null,
    recipeComplexity: 1,
    recipeSuggestionScore: null,
    recipeTimeInMinutes: 1,
    obligatoryIngredientsAmount: 0,
    matchingIngredients: [2, 13],
    missingIngredients: [29],
    suggestionScore: 0.6666666666666666,
  },
];

export const suggestedIngredientsExample: IIngredient[] = [
  {
    ingredientId: 2,
    ingredientName: "Ingredient2",
    ingredientCategoryId: 1,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
  {
    ingredientId: 3,
    ingredientName: "Ingredient3",
    ingredientCategoryId: 1,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
  {
    ingredientId: 13,
    ingredientName: "Ingredient13",
    ingredientCategoryId: 2,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
  {
    ingredientId: 17,
    ingredientName: "Ingredient17",
    ingredientCategoryId: 2,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
  {
    ingredientId: 23,
    ingredientName: "Ingredient23",
    ingredientCategoryId: 3,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
  {
    ingredientId: 29,
    ingredientName: "Ingredient29",
    ingredientCategoryId: 3,
    appearanceInRecipesTimes: 0,
    commonnessFromUsers: 0,
    additionScore: 0,
    defaultUnit: "g",
  },
];
